/* tslint:disable:no-unused-locals */
import { ZObject } from "zapier-platform-core";
import { ObjectSerializer } from "../model/models";
import { generateInputFields, transformInputData, InputBundle } from "./apis";
import { addHeaders } from "../authentication";

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

const contactCreateInput = [
  {
    key: "workspaceId",
    required: true,
    label: "Workspace ID",
    helpText: "The identifier for the workspace.",
    dynamic: "workspaces.id.projectName",
  },
  {
    key: "firstName",
    required: true,
    label: "First Name",
    helpText: "The first name of the contact",
  },
  {
    key: "lastName",
    required: true,
    label: "Last Name",
    helpText: "The last name of the contact.",
  },
  {
    key: "workMobilePhone1",
    required: true,
    label: "Work Mobile Phone 1",
    helpText: "The primary work mobile number of the contact.",
  },
  {
    key: "workEmailAddress1",
    required: true,
    label: "Work Email Address 1",
    helpText: "The primary work email address of the contact.",
  },
  {
    key: "workCountry",
    required: true,
    label: "Work Country",
    helpText: "The work country of the contact.",
  },
  {
    key: "timezone",
    required: true,
    label: "Time Zone",
    placeholder: "Australia/Melbourne",
    helpText:
      "The time zone in which the contact lives. Values are relative to GMT, please use Timezone ID format e.g Australia/Melbourne",
  },
  {
    key: "title",
    required: false,
    label: "Title",
    helpText: "The title to address the contact with.",
  },
  {
    key: "workMobilePhone2",
    required: false,
    label: "Work Mobile Phone 2",
    helpText: "The secondary work mobile number of the contact.",
  },
  {
    key: "workEmailAddress2",
    required: false,
    label: "Work Email Address 2",
    helpText: "The secondary work email address of the contact.",
  },
  {
    key: "workPhoneAreaCode1",
    required: false,
    label: "Work Phone Area Code 1",
    helpText: "The primary work phone number area code of the contact.",
  },
  {
    key: "workPhone1",
    required: false,
    label: "Work Phone 1",
    helpText: "The primary work phone number of the contact.",
  },
  {
    key: "workPhoneAreaCode2",
    required: false,
    label: "Work Phone Area Code 2",
    helpText: "The secondary work phone number area code of the contact.",
  },
  {
    key: "workPhone2",
    required: false,
    label: "Work Phone 2",
    helpText: "The secondary work phone number of the contact.",
  },
  {
    key: "workFaxAreaCode1",
    required: false,
    label: "Work Fax Area Code1",
    helpText: "The work fax number area code of the contact.",
  },
  {
    key: "workFax1",
    required: false,
    label: "Work Fax 1",
    helpText: "The work fax number of the contact.",
  },
  {
    key: "workSatellitePhone",
    required: false,
    label: "Work Satellite Phone",
    helpText: "The work satellite phone number of the contact.",
  },
  {
    key: "workOtherPhone",
    required: false,
    label: "Work Other Phone",
    helpText: "The work other phone number of the contact.",
  },
  {
    key: "workAddress1",
    required: false,
    label: "Work Address 1",
    helpText: "The first work address line of the contact.",
  },
  {
    key: "workAddress2",
    required: false,
    label: "Work Address 2",
    helpText: "The second work address line of the contact.",
  },
  {
    key: "workSuburb",
    required: false,
    label: "Work Suburb",
    helpText: "The work address suburb of the contact.",
  },
  {
    key: "workState",
    required: false,
    label: "Work State",
    helpText: "The work address state of the contact.",
  },
  {
    key: "workPostCode",
    required: false,
    label: "Work Post Code",
    helpText: "The work address post code of the contact.",
  },
  {
    key: "workPostalAddress1",
    required: false,
    label: "Work Postal Address 1",
    helpText: "The first work postal address line of the contact.",
  },
  {
    key: "workPostalAddress2",
    required: false,
    label: "Work Postal Address 2",
    helpText: "The second work postal address line of the contact.",
  },
  {
    key: "workPostalSuburb",
    required: false,
    label: "Work Postal Suburb",
    helpText: "The work postal address suburb of the contact.",
  },
  {
    key: "workPostalState",
    required: false,
    label: "Work Postal State",
    helpText: "The work postal address state of the contact.",
  },
  {
    key: "workPostalPostCode",
    required: false,
    label: "Work Postal PostCode",
    helpText: "The work postal address post code of the contact",
  },
  {
    key: "personalEmailAddress1",
    required: false,
    label: "Personal Email Address 1",
    helpText: "The primary personal email address of the contact.",
  },
  {
    key: "personalEmailAddress2",
    required: false,
    label: "Personal Email Address 2",
    helpText: "The secondary personal email address of the contact.",
  },
  {
    key: "personalAddress1",
    required: false,
    label: "Personal Address 1",
    helpText: "The first personal address line of the contact.",
  },
  {
    key: "personalAddress2",
    required: false,
    label: "Personal Address 2",
    helpText: "The second personal address line of the contact.",
  },
  {
    key: "personalSuburb",
    required: false,
    label: "Personal Suburb",
    helpText: "The personal address suburb of the contact.",
  },
  {
    key: "personalState",
    required: false,
    label: "Personal State",
    helpText: "The personal address state of the contact.",
  },
  {
    key: "personalPostCode",
    required: false,
    label: "Personal Post Code",
    helpText: "The personal address post code of the contact.",
  },
  {
    key: "personalCountry",
    required: false,
    label: "Personal Country",
    helpText: "The personal address country of the contact.",
  },
  {
    key: "personalPhoneAreaCode1",
    required: false,
    label: "Personal PhoneArea Code 1",
    helpText: "The primary personal phone number area code of the contact.",
  },
  {
    key: "personalPhone1",
    required: false,
    label: "Personal Phone 1",
    helpText: "The primary personal phone number of the contact.",
  },
  {
    key: "personalPhoneAreaCode2",
    required: false,
    label: "Personal PhoneArea Code 2",
    helpText: "The secondary personal phone number area code of the contact.",
  },
  {
    key: "personalPhone2",
    required: false,
    label: "Personal Phone 2",
    helpText: "The secondary personal phone number of the contact.",
  },
  {
    key: "personalFaxAreaCode1",
    required: false,
    label: "Personal FaxArea Code1",
    helpText: "The personal fax number area code of the contact.",
  },
  {
    key: "personalFax1",
    required: false,
    label: "Personal Fax 1",
    helpText: "The personal fax number of the contact.",
  },
  {
    key: "otherPhoneAreaCode1",
    required: false,
    label: "Other Phone Area Code 1",
    helpText: "The other phone number area code of the contact.",
  },
  {
    key: "otherPhone1",
    required: false,
    label: "Other Phone 1",
    helpText: "The other phone number of the contact.",
  },
  {
    key: "otherMobile",
    required: false,
    label: "Other Mobile",
    helpText: "The other mobile number of the contact.",
  },
  {
    key: "otherFirstName",
    required: false,
    label: "Other First Name",
    helpText: "The other first name of the contact.",
  },
  {
    key: "otherLastName",
    required: false,
    label: "Other Last Name",
    helpText: "The other last name of the contact.",
  },
  {
    key: "otherTitle",
    required: false,
    label: "Other Title",
    helpText: "The other title to address the contact with.",
  },
  {
    key: "status",
    required: false,
    label: "Status",
    helpText: "The validity status of the contact, either Active or Disabled.",
    choices: {
      Active: "A",
      Disabled: "D",
    },
  },
  {
    key: "companyName",
    required: false,
    label: "Company Name",
    helpText: "The company name of the contact.",
  },
  {
    key: "jobTitle",
    required: false,
    label: "Job Title",
    helpText: "The job title of the contact.",
  },
  {
    key: "division",
    required: false,
    label: "Division",
    helpText: "The division in the company to which the contact is associated.",
  },
  {
    key: "businessUnit",
    required: false,
    label: "Business Unit",
    helpText: "The business unit in the company to which the contact is associated.",
  },
  {
    key: "department",
    required: false,
    label: "Department",
    helpText: "The department in the company to which the contact is associated",
  },
  {
    key: "teamName1",
    required: false,
    label: "Team Name 1",
    helpText: "The primary team name of the contact.",
  },
  {
    key: "teamName2",
    required: false,
    label: "Team Name 2",
    helpText: "The secondary team name of the contact.",
  },
  {
    key: "role1",
    required: false,
    label: "Role1",
    helpText: "The primary role of the contact.",
  },
  {
    key: "role2",
    required: false,
    label: "Role2",
    helpText: "The secondary role of the contact.",
  },
  {
    key: "locations",
    required: false,
    label: "Locations",
    children: [
      {
        key: "latitude",
        required: false,
        label: "Latitude",
        helpText: "The measurement of distance north or south of the Equator, for the contact.",
      },
      {
        key: "longitude",
        required: false,
        label: "Longitude",
        helpText: "The measurement of distance east or west of the prime meridian, for the contact.",
      },
      {
        key: "type",
        required: false,
        label: "Type",
        helpText: "A description for the location. At least one element of the locations array must have a type equal to CurrentLocation",
      },
    ],
  },
  {
    key: "messagingoptions",
    required: false,
    label: "Messaging Options",
    children: [
      {
        key: "channel",
        required: false,
        label: "Channel",
        helpText: "A boolean flag indicating whether messaging is enabled for the channel",
        choices: {
          sms: "sms",
          email: "email",
          voice: "voice",
        },
      },
      {
        key: "enabled",
        required: false,
        label: "Enabled",
        helpText: "A boolean flag indicating whether messaging is enabled for the channel",
      },
      {
        key: "primary",
        required: false,
        label: "Primary",
        helpText: "The primary contact address for the channel",
        choices: {
          WorkMobilePhone1: "WorkMobilePhone1",
          WorkMobilePhone2: "WorkMobilePhone2",
          WorkEmailAddress1: "WorkEmailAddress1",
          WorkEmailAddress2: "WorkEmailAddress2",
          PersonalMobilePhone1: "PersonalMobilePhone1",
          PersonalEmailAddress1: "PersonalEmailAddress1",
        },
      },
      {
        key: "secondary",
        required: false,
        label: "Secondary",
        helpText: "The secondary contact address for the channel",
        choices: {
          WorkMobilePhone1: "WorkMobilePhone1",
          WorkMobilePhone2: "WorkMobilePhone2",
          WorkEmailAddress1: "WorkEmailAddress1",
          WorkEmailAddress2: "WorkEmailAddress2",
          PersonalMobilePhone1: "PersonalMobilePhone1",
          PersonalEmailAddress1: "PersonalEmailAddress1",
        },
      },
      {
        key: "tertiary",
        required: false,
        label: "Tertiary",
        helpText: "The tertiary contact address for the channel",
        choices: {
          WorkMobilePhone1: "WorkMobilePhone1",
          WorkMobilePhone2: "WorkMobilePhone2",
          WorkEmailAddress1: "WorkEmailAddress1",
          WorkEmailAddress2: "WorkEmailAddress2",
          PersonalMobilePhone1: "PersonalMobilePhone1",
          PersonalEmailAddress1: "PersonalEmailAddress1",
        },
      },
    ],
  },
] as const;

const contactDeleteInput = [
  {
    key: "workspaceId",
    required: true,
    label: "workspaceId",
    helpText: "Test",
  },
  {
    key: "contactId",
    required: true,
    label: "contactId",
    helpText: "Test",
  },
  {
    key: "action",
    required: false,
    label: "action",
    helpText: "Test",
    choices: {
      deleteAll: "deleteAll",
    },
  },
] as const;

const contactListInput = [
  {
    key: "workspaceId",
    required: true,
    label: "workspaceId",
    helpText: "Test",
    dynamic: "workspaces.id.projectName",
  },
  {
    key: "limit",
    required: false,
    label: "limit",
    helpText: "Test",
  },
  {
    key: "offset",
    required: false,
    label: "offset",
    helpText: "Test",
  },
  {
    key: "sortOrder",
    required: false,
    label: "sortOrder",
    helpText: "Test",
    choices: {
      asc: "asc",
      desc: "desc",
    },
  },
  {
    key: "sortFields",
    required: false,
    label: "sortFields",
    helpText: "Test",
  },
  {
    key: "fieldname",
    required: false,
    label: "fieldname",
    helpText: "Test",
  },
  {
    key: "customFields",
    required: false,
    label: "customFields",
    helpText: "Test",
  },
] as const;

const contactRetrieveInput = [
  {
    key: "workspaceId",
    required: true,
    label: "workspaceId",
    helpText: "Test",
    dynamic: "workspaces.id.projectName",
  },
  {
    key: "contactId",
    required: true,
    label: "contactId",
    helpText: "Test",
  },
  {
    key: "fields",
    required: false,
    label: "fields",
    helpText: "Test",
  },
  {
    key: "sortOrder",
    required: false,
    label: "sortOrder",
    helpText: "Test",
    choices: {
      asc: "asc",
      desc: "desc",
    },
  },
  {
    key: "sortFields",
    required: false,
    label: "sortFields",
    helpText: "Test",
  },
] as const;

const contactUpdateInput = [
  {
    key: "workspaceId",
    required: true,
    label: "workspaceId",
    helpText: "Test",
    dynamic: "workspaces.id.projectName",
  },
  {
    key: "contactId",
    required: true,
    label: "contactId",
    helpText: "Test",
    dynamic: "contacts.id.firstName",
  },
  {
    key: "firstName",
    required: true,
    label: "FirstName",
    helpText: "Test",
  },
  {
    key: "lastName",
    required: true,
    label: "LastName",
    helpText: "Test",
  },
  {
    key: "workMobilePhone1",
    required: true,
    label: "WorkMobilePhone1",
    helpText: "Test",
  },
  {
    key: "workEmailAddress1",
    required: true,
    label: "WorkEmailAddress1",
    helpText: "Test",
  },
  {
    key: "workCountry",
    required: true,
    label: "WorkCountry",
    helpText: "Test",
  },
  {
    key: "timezone",
    required: true,
    label: "Timezone",
    helpText: "Test",
  },
  {
    key: "title",
    required: false,
    label: "Title",
    helpText: "Test",
  },
  {
    key: "workMobilePhone2",
    required: false,
    label: "WorkMobilePhone2",
    helpText: "Test",
  },
  {
    key: "workEmailAddress2",
    required: false,
    label: "WorkEmailAddress2",
    helpText: "Test",
  },
  {
    key: "workPhoneAreaCode1",
    required: false,
    label: "WorkPhoneAreaCode1",
    helpText: "Test",
  },
  {
    key: "workPhone1",
    required: false,
    label: "WorkPhone1",
    helpText: "Test",
  },
  {
    key: "workPhoneAreaCode2",
    required: false,
    label: "WorkPhoneAreaCode2",
    helpText: "Test",
  },
  {
    key: "workPhone2",
    required: false,
    label: "WorkPhone2",
    helpText: "Test",
  },
  {
    key: "workFaxAreaCode1",
    required: false,
    label: "WorkFaxAreaCode1",
    helpText: "Test",
  },
  {
    key: "workFax1",
    required: false,
    label: "WorkFax1",
    helpText: "Test",
  },
  {
    key: "workSatellitePhone",
    required: false,
    label: "WorkSatellitePhone",
    helpText: "Test",
  },
  {
    key: "workOtherPhone",
    required: false,
    label: "WorkOtherPhone",
    helpText: "Test",
  },
  {
    key: "workAddress1",
    required: false,
    label: "WorkAddress1",
    helpText: "Test",
  },
  {
    key: "workAddress2",
    required: false,
    label: "WorkAddress2",
    helpText: "Test",
  },
  {
    key: "workSuburb",
    required: false,
    label: "WorkSuburb",
    helpText: "Test",
  },
  {
    key: "workState",
    required: false,
    label: "WorkState",
    helpText: "Test",
  },
  {
    key: "workPostCode",
    required: false,
    label: "WorkPostCode",
    helpText: "Test",
  },
  {
    key: "workPostalAddress1",
    required: false,
    label: "WorkPostalAddress1",
    helpText: "Test",
  },
  {
    key: "workPostalAddress2",
    required: false,
    label: "WorkPostalAddress2",
    helpText: "Test",
  },
  {
    key: "workPostalSuburb",
    required: false,
    label: "WorkPostalSuburb",
    helpText: "Test",
  },
  {
    key: "workPostalState",
    required: false,
    label: "WorkPostalState",
    helpText: "Test",
  },
  {
    key: "workPostalPostCode",
    required: false,
    label: "WorkPostalPostCode",
    helpText: "Test",
  },
  {
    key: "personalEmailAddress1",
    required: false,
    label: "PersonalEmailAddress1",
    helpText: "Test",
  },
  {
    key: "personalEmailAddress2",
    required: false,
    label: "PersonalEmailAddress2",
    helpText: "Test",
  },
  {
    key: "personalAddress1",
    required: false,
    label: "PersonalAddress1",
    helpText: "Test",
  },
  {
    key: "personalAddress2",
    required: false,
    label: "PersonalAddress2",
    helpText: "Test",
  },
  {
    key: "personalSuburb",
    required: false,
    label: "PersonalSuburb",
    helpText: "Test",
  },
  {
    key: "personalState",
    required: false,
    label: "PersonalState",
    helpText: "Test",
  },
  {
    key: "personalPostCode",
    required: false,
    label: "PersonalPostCode",
    helpText: "Test",
  },
  {
    key: "personalCountry",
    required: false,
    label: "PersonalCountry",
    helpText: "Test",
  },
  {
    key: "personalPhoneAreaCode1",
    required: false,
    label: "PersonalPhoneAreaCode1",
    helpText: "Test",
  },
  {
    key: "personalPhone1",
    required: false,
    label: "PersonalPhone1",
    helpText: "Test",
  },
  {
    key: "personalPhoneAreaCode2",
    required: false,
    label: "PersonalPhoneAreaCode2",
    helpText: "Test",
  },
  {
    key: "personalPhone2",
    required: false,
    label: "PersonalPhone2",
    helpText: "Test",
  },
  {
    key: "personalFaxAreaCode1",
    required: false,
    label: "PersonalFaxAreaCode1",
    helpText: "Test",
  },
  {
    key: "personalFax1",
    required: false,
    label: "PersonalFax1",
    helpText: "Test",
  },
  {
    key: "otherPhoneAreaCode1",
    required: false,
    label: "OtherPhoneAreaCode1",
    helpText: "Test",
  },
  {
    key: "otherPhone1",
    required: false,
    label: "OtherPhone1",
    helpText: "Test",
  },
  {
    key: "otherMobile",
    required: false,
    label: "OtherMobile",
    helpText: "Test",
  },
  {
    key: "otherFirstName",
    required: false,
    label: "OtherFirstName",
    helpText: "Test",
  },
  {
    key: "otherLastName",
    required: false,
    label: "OtherLastName",
    helpText: "Test",
  },
  {
    key: "otherTitle",
    required: false,
    label: "OtherTitle",
    helpText: "Test",
  },
  {
    key: "status",
    required: false,
    label: "Status",
    helpText: "Test",
    choices: {
      A: "A",
      D: "D",
    },
  },
  {
    key: "companyName",
    required: false,
    label: "CompanyName",
    helpText: "Test",
  },
  {
    key: "jobTitle",
    required: false,
    label: "JobTitle",
    helpText: "Test",
  },
  {
    key: "division",
    required: false,
    label: "Division",
    helpText: "Test",
  },
  {
    key: "businessUnit",
    required: false,
    label: "BusinessUnit",
    helpText: "Test",
  },
  {
    key: "department",
    required: false,
    label: "Department",
    helpText: "Test",
  },
  {
    key: "teamName1",
    required: false,
    label: "TeamName1",
    helpText: "Test",
  },
  {
    key: "teamName2",
    required: false,
    label: "TeamName2",
    helpText: "Test",
  },
  {
    key: "role1",
    required: false,
    label: "Role1",
    helpText: "Test",
  },
  {
    key: "role2",
    required: false,
    label: "Role2",
    helpText: "Test",
  },
  {
    key: "locations",
    required: false,
    label: "Locations",
    children: [
      {
        key: "latitude",
        required: false,
        label: "Latitude",
        helpText: "Test",
      },
      {
        key: "longitude",
        required: false,
        label: "Longitude",
        helpText: "Test",
      },
      {
        key: "type",
        required: false,
        label: "Type",
        helpText: "Test",
      },
    ],
  },
  {
    key: "messagingoptions",
    required: false,
    label: "Messagingoptions",
    children: [
      {
        key: "channel",
        required: false,
        label: "Channel",
        helpText: "Test",
        choices: {
          sms: "sms",
          email: "email",
          voice: "voice",
        },
      },
      {
        key: "enabled",
        required: false,
        label: "Enabled",
        helpText: "Test",
      },
      {
        key: "primary",
        required: false,
        label: "Primary",
        helpText: "Test",
        choices: {
          WorkMobilePhone1: "WorkMobilePhone1",
          WorkMobilePhone2: "WorkMobilePhone2",
          WorkEmailAddress1: "WorkEmailAddress1",
          WorkEmailAddress2: "WorkEmailAddress2",
          PersonalMobilePhone1: "PersonalMobilePhone1",
          PersonalEmailAddress1: "PersonalEmailAddress1",
        },
      },
      {
        key: "secondary",
        required: false,
        label: "Secondary",
        helpText: "Test",
        choices: {
          WorkMobilePhone1: "WorkMobilePhone1",
          WorkMobilePhone2: "WorkMobilePhone2",
          WorkEmailAddress1: "WorkEmailAddress1",
          WorkEmailAddress2: "WorkEmailAddress2",
          PersonalMobilePhone1: "PersonalMobilePhone1",
          PersonalEmailAddress1: "PersonalEmailAddress1",
        },
      },
      {
        key: "tertiary",
        required: false,
        label: "Tertiary",
        helpText: "Test",
        choices: {
          WorkMobilePhone1: "WorkMobilePhone1",
          WorkMobilePhone2: "WorkMobilePhone2",
          WorkEmailAddress1: "WorkEmailAddress1",
          WorkEmailAddress2: "WorkEmailAddress2",
          PersonalMobilePhone1: "PersonalMobilePhone1",
          PersonalEmailAddress1: "PersonalEmailAddress1",
        },
      },
    ],
  },
] as const;

export const ContactsApi = {
  key: "contacts",
  noun: "Contacts",
  create: {
    display: {
      label: "Create Contact",
      description:
        "Creates a Contact object. The Contact can be used as a recipient when sending multi-channel messages.",
    },
    operation: {
      inputFields: generateInputFields(contactCreateInput),
      perform: async (
        z: ZObject,
        bundle: InputBundle<typeof contactCreateInput>
      ) => {
        const { workspaceId, ...contact } = transformInputData(
          bundle.inputData
        );

        const localVarPath =
          bundle.authData.host +
          "/workspaces/{workspaceId}/contacts".replace(
            "{" + "workspaceId" + "}",
            encodeURIComponent(String(workspaceId))
          );
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = {};

        let localVarFormParams: any = {};
        localVarHeaderParams["Accept"] =
          "application/vnd.whispir.contact-v1+json";
        localVarHeaderParams["Content-Type"] =
          "application/vnd.whispir.contact-v1+json";

        let localVarUseFormData = false;

        const responsePromise = z.request({
          method: "POST",
          headers: addHeaders(localVarHeaderParams, bundle),
          params: localVarQueryParameters,
          url: localVarPath,
          body: ObjectSerializer.serialize(contact, "Contact"),
        });
        return responsePromise.then((response) => {
          if (
            response.status &&
            response.status >= 200 &&
            response.status <= 299
          ) {
            let body = {};
            body = ObjectSerializer.deserialize(response.data, "Contact");

            // Special case to extract the resource identifier from the `Location` header.
            const checkLocation =
              response?.headers?.location?.match(/\/([^\/]+)\/?$/);
            let id =
              checkLocation && checkLocation[1] ? checkLocation[1] : undefined;

            return { id, ...body };
          } else {
            throw new z.errors.Error(response.data);
          }
        });
      },
    },
  },
  search: {
    display: {
      label: "Retrieve a contact",
      description: "Get a contact by ID.",
      hidden: true,
    },
    operation: {
      inputFields: generateInputFields(contactRetrieveInput),
      perform: async (
        z: ZObject,
        bundle: InputBundle<typeof contactRetrieveInput>
      ) => {
        const { workspaceId, contactId } = transformInputData(bundle.inputData);

        const localVarPath =
          bundle.authData.host +
          "/workspaces/{workspaceId}/contacts".replace(
            "{" + "workspaceId" + "}",
            encodeURIComponent(String(workspaceId))
          ) +
          "/" +
          encodeURIComponent(String(contactId));

        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = {};

        let localVarFormParams: any = {};
        localVarHeaderParams["Accept"] =
          "application/vnd.whispir.contact-v1+json";
        localVarHeaderParams["Content-Type"] =
          "application/vnd.whispir.contact-v1+json";

        let localVarUseFormData = false;

        const responsePromise = z.request({
          method: "GET",
          headers: addHeaders(localVarHeaderParams, bundle),
          params: localVarQueryParameters,
          url: localVarPath,
        });
        return responsePromise.then((response) => {
          if (
            response.status &&
            response.status >= 200 &&
            response.status <= 299
          ) {
            return { id: contactId, ...response.data };
          } else {
            throw new z.errors.Error(response.data);
          }
        });
      },
    },
  },
  list: {
    display: {
      label: "List Contacts",
      hidden: true,
      description: "List available contacts in a given workspace",
    },
    operation: {
      inputFields: generateInputFields(contactListInput),
      perform: async (
        z: ZObject,
        bundle: InputBundle<typeof contactListInput>
      ) => {
        const { workspaceId } = transformInputData(bundle.inputData);

        const localVarPath =
          bundle.authData.host +
          "/workspaces/{workspaceId}/contacts".replace(
            "{" + "workspaceId" + "}",
            encodeURIComponent(String(workspaceId))
          );

        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = {};

        let localVarFormParams: any = {};
        localVarHeaderParams["Content-Type"] =
          "application/vnd.whispir.contact-v1+json";
        localVarHeaderParams["Accept"] =
          "application/vnd.whispir.contact-v1+json";

        let localVarUseFormData = false;

        const responsePromise = z.request({
          method: "GET",
          headers: addHeaders(localVarHeaderParams, bundle),
          params: localVarQueryParameters,
          url: localVarPath,
        });

        return responsePromise.then((response) => {
          if (
            response.status &&
            response.status >= 200 &&
            response.status <= 299
          ) {
            const { contacts } = response.data;
            return contacts;
          } else {
            throw new z.errors.Error(response.data);
          }
        });
      },
    },
  },
};
