/* tslint:disable:no-unused-locals */
import { ZObject } from 'zapier-platform-core'
import { ObjectSerializer } from '../model/models';
import { generateInputFields, transformInputData, InputBundle } from './apis';
import { addHeaders } from '../authentication';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

const customListListInput = [
    {
        key: 'limit',
        required: false,
        label: 'limit',
        helpText: 'Test',
    },
    {
        key: 'offset',
        required: false,
        label: 'offset',
        helpText: 'Test',
    },
    {
        key: 'sortOrder',
        required: false,
        label: 'sortOrder',
        helpText: 'Test',
        choices: {
            'asc': 'asc',
            'desc': 'desc',
        },
    },
    {
        key: 'sortFields',
        required: false,
        label: 'sortFields',
        helpText: 'Test',
    },
    {
        key: 'name',
        required: false,
        label: 'name',
        helpText: 'Test',
    },
    {
        key: 'type',
        required: false,
        label: 'type',
        helpText: 'Test',
        choices: {
            'INCIDENT': 'INCIDENT',
            'MESSAGE': 'MESSAGE',
            'CONTACT': 'CONTACT',
            'RSS': 'RSS',
        },
    },
] as const;

const customListRetrieveInput = [
    {
        key: 'customlistId',
        required: true,
        label: 'customlistId',
        helpText: 'Test',
    },
] as const;


export const CustomListsApi = {
  key: 'customLists',
  noun: 'CustomLists',
};
