/* tslint:disable:no-unused-locals */
import { ZObject } from 'zapier-platform-core'
import { ObjectSerializer } from '../model/models';
import { generateInputFields, transformInputData, InputBundle } from './apis';
import { addHeaders } from '../authentication';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

const importCreateInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'resourceId',
        required: true,
        label: 'ResourceId',
        helpText: 'Test',
    },
    {
        key: 'importType',
        required: true,
        label: 'ImportType',
        helpText: 'Test',
    },
    {
        key: 'importOptions',
        required: true,
        label: 'ImportOptions',
        properties: [
                {
        key: 'firstName',
        required: true,
        label: 'FirstName',
        helpText: 'Test',
    },
    {
        key: 'lastName',
        required: true,
        label: 'LastName',
        helpText: 'Test',
    },
    {
        key: 'workMobilePhone1',
        required: true,
        label: 'WorkMobilePhone1',
        helpText: 'Test',
    },
    {
        key: 'workCountry',
        required: true,
        label: 'WorkCountry',
        helpText: 'Test',
    },
    {
        key: 'timezone',
        required: true,
        label: 'Timezone',
        helpText: 'Test',
    },

        ],
    },
    {
        key: 'importMode',
        required: true,
        label: 'ImportMode',
        helpText: 'Test',
        choices: {
                'replace': 'replace',
                'duplicate': 'duplicate',
                'ignore': 'ignore',
        }
    },

] as const;


export const ImportsApi = {
  key: 'imports',
  noun: 'Imports',
  create: {
    display: {
        label: 'Create a Imports',
        description: 'Test'
    },
    operation: {
        inputFields: generateInputFields(importCreateInput),
        perform: async (z: ZObject, bundle: InputBundle<typeof importCreateInput>) => {
            const {
                workspaceId,
                ..._import
            } = transformInputData(bundle.inputData);

            const localVarPath = bundle.authData.host + '/workspaces/{workspaceId}/imports'
                .replace('{' + 'workspaceId' + '}', encodeURIComponent(String(workspaceId)));
            let localVarQueryParameters: any = {};
            let localVarHeaderParams: any = {};

            let localVarFormParams: any = {};
            localVarHeaderParams['Content-Type'] = 'application/vnd.whispir.importcontact-v1+json';
            localVarHeaderParams['Accept'] = 'application/vnd.whispir.importcontact-v1+json';

            let localVarUseFormData = false;

            const responsePromise = z.request({
                method: 'POST',
                headers: addHeaders(localVarHeaderParams, bundle),
                params: localVarQueryParameters,
                url: localVarPath,
                body: ObjectSerializer.serialize(_import, "Import")
            });
            return responsePromise
                .then(response => {
                    if (response.status && response.status >= 200 && response.status <= 299) {
                            let body = {};
                            
                            // Special case to extract the resource identifier from the `Location` header.
                            const checkLocation = response?.headers?.location?.match(/\/([^\/]+)\/?$/);
                            let id = (checkLocation && checkLocation[1]) ? checkLocation[1] : undefined;
                            
                            return { id, ...body };
                    } else {
                            throw new z.errors.Error(response.data);
                    }
                });
        },
    }
  },
};
