/* tslint:disable:no-unused-locals */
import { ZObject } from 'zapier-platform-core'
import { ObjectSerializer } from '../model/models';
import { generateInputFields, transformInputData, InputBundle } from './apis';
import { addHeaders } from '../authentication';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

const resourceCreateInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'name',
        required: true,
        label: 'Name',
        helpText: 'Test',
    },
    {
        key: 'scope',
        required: true,
        label: 'Scope',
        helpText: 'Test',
        choices: {
                'private': 'private',
                'public': 'public',
        }
    },
    {
        key: 'mimeType',
        required: true,
        label: 'MimeType',
        helpText: 'Test',
    },
    {
        key: 'derefUri',
        required: true,
        label: 'DerefUri',
        helpText: 'Test',
    },

] as const;

const resourceDeleteInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'resourceId',
        required: true,
        label: 'resourceId',
        helpText: 'Test',
    },
] as const;

const resourceListInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'limit',
        required: false,
        label: 'limit',
        helpText: 'Test',
    },
    {
        key: 'offset',
        required: false,
        label: 'offset',
        helpText: 'Test',
    },
    {
        key: 'sortOrder',
        required: false,
        label: 'sortOrder',
        helpText: 'Test',
        choices: {
            'asc': 'asc',
            'desc': 'desc',
        },
    },
    {
        key: 'sortFields',
        required: false,
        label: 'sortFields',
        helpText: 'Test',
    },
    {
        key: 'scope',
        required: false,
        label: 'scope',
        helpText: 'Test',
        choices: {
            'private': 'private',
            'public': 'public',
        },
    },
    {
        key: 'name',
        required: false,
        label: 'name',
        helpText: 'Test',
    },
] as const;

const resourceRetrieveInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'resourceId',
        required: true,
        label: 'resourceId',
        helpText: 'Test',
    },
] as const;

const resourceUpdateInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'resourceId',
        required: true,
        label: 'resourceId',
        helpText: 'Test',
    },
    {
        key: 'name',
        required: true,
        label: 'Name',
        helpText: 'Test',
    },
    {
        key: 'scope',
        required: true,
        label: 'Scope',
        helpText: 'Test',
        choices: {
                'private': 'private',
                'public': 'public',
        }
    },
    {
        key: 'mimeType',
        required: true,
        label: 'MimeType',
        helpText: 'Test',
    },
    {
        key: 'derefUri',
        required: true,
        label: 'DerefUri',
        helpText: 'Test',
    },

] as const;


export const ResourcesApi = {
  key: 'resources',
  noun: 'Resources',
  create: {
    display: {
        label: 'Create a Resources',
        description: 'Test'
    },
    operation: {
        inputFields: generateInputFields(resourceCreateInput),
        perform: async (z: ZObject, bundle: InputBundle<typeof resourceCreateInput>) => {
            const {
                workspaceId,
                ...resource
            } = transformInputData(bundle.inputData);

            const localVarPath = bundle.authData.host + '/workspaces/{workspaceId}/resources'
                .replace('{' + 'workspaceId' + '}', encodeURIComponent(String(workspaceId)));
            let localVarQueryParameters: any = {};
            let localVarHeaderParams: any = {};

            let localVarFormParams: any = {};
            localVarHeaderParams['Content-Type'] = 'application/vnd.whispir.resource-v1+json';
            localVarHeaderParams['Accept'] = 'application/vnd.whispir.resource-v1+json';

            let localVarUseFormData = false;

            const responsePromise = z.request({
                method: 'POST',
                headers: addHeaders(localVarHeaderParams, bundle),
                params: localVarQueryParameters,
                url: localVarPath,
                body: ObjectSerializer.serialize(resource, "Resource")
            });
            return responsePromise
                .then(response => {
                    if (response.status && response.status >= 200 && response.status <= 299) {
                            let body = {};
                            body = ObjectSerializer.deserialize(response.data, "Resource");
                            
                            // Special case to extract the resource identifier from the `Location` header.
                            const checkLocation = response?.headers?.location?.match(/\/([^\/]+)\/?$/);
                            let id = (checkLocation && checkLocation[1]) ? checkLocation[1] : undefined;
                            
                            return { id, ...body };
                    } else {
                            throw new z.errors.Error(response.data);
                    }
                });
        },
    }
  },
};
