/* tslint:disable:no-unused-locals */
import { ZObject } from 'zapier-platform-core'
import { ObjectSerializer } from '../model/models';
import { generateInputFields, transformInputData, InputBundle } from './apis';
import { addHeaders } from '../authentication';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

const reponseRuleListInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'limit',
        required: false,
        label: 'limit',
        helpText: 'Test',
    },
    {
        key: 'offset',
        required: false,
        label: 'offset',
        helpText: 'Test',
    },
    {
        key: 'sortOrder',
        required: false,
        label: 'sortOrder',
        helpText: 'Test',
        choices: {
            'asc': 'asc',
            'desc': 'desc',
        },
    },
    {
        key: 'sortFields',
        required: false,
        label: 'sortFields',
        helpText: 'Test',
    },
] as const;

const responseRuleCreateInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'name',
        required: true,
        label: 'Name',
        helpText: 'Test',
    },
    {
        key: 'description',
        required: false,
        label: 'Description',
        helpText: 'Test',
    },
    {
        key: 'responseTemplatePatterns',
        required: true,
        label: 'ResponseTemplatePatterns',
        properties: [
                {
        key: 'name',
        required: true,
        label: 'Name',
        helpText: 'Test',
    },
    {
        key: 'pattern',
        required: true,
        label: 'Pattern',
        helpText: 'Test',
    },
    {
        key: 'textPrompt',
        required: true,
        label: 'TextPrompt',
        helpText: 'Test',
    },
    {
        key: 'voicePrompt',
        required: true,
        label: 'VoicePrompt',
        helpText: 'Test',
    },
    {
        key: 'spokenVoicePrompt',
        required: true,
        label: 'SpokenVoicePrompt',
        helpText: 'Test',
    },
    {
        key: 'colour',
        required: true,
        label: 'Colour',
        helpText: 'Test',
    },

        ],
    },

] as const;

const responseRuleDeleteInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'responseRuleId',
        required: true,
        label: 'responseRuleId',
        helpText: 'Test',
    },
] as const;

const responseRuleRetrieveInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'responseRuleId',
        required: true,
        label: 'responseRuleId',
        helpText: 'Test',
    },
] as const;

const responseRuleUpdateInput = [
    {
        key: 'workspaceId',
        required: true,
        label: 'workspaceId',
        helpText: 'Test',
    },
    {
        key: 'responseRuleId',
        required: true,
        label: 'responseRuleId',
        helpText: 'Test',
    },
    {
        key: 'name',
        required: true,
        label: 'Name',
        helpText: 'Test',
    },
    {
        key: 'description',
        required: false,
        label: 'Description',
        helpText: 'Test',
    },
    {
        key: 'responseTemplatePatterns',
        required: true,
        label: 'ResponseTemplatePatterns',
        properties: [
                {
        key: 'name',
        required: true,
        label: 'Name',
        helpText: 'Test',
    },
    {
        key: 'pattern',
        required: true,
        label: 'Pattern',
        helpText: 'Test',
    },
    {
        key: 'textPrompt',
        required: true,
        label: 'TextPrompt',
        helpText: 'Test',
    },
    {
        key: 'voicePrompt',
        required: true,
        label: 'VoicePrompt',
        helpText: 'Test',
    },
    {
        key: 'spokenVoicePrompt',
        required: true,
        label: 'SpokenVoicePrompt',
        helpText: 'Test',
    },
    {
        key: 'colour',
        required: true,
        label: 'Colour',
        helpText: 'Test',
    },

        ],
    },

] as const;


export const ResponseRulesApi = {
  key: 'responseRules',
  noun: 'ResponseRules',
  create: {
    display: {
        label: 'Create a ResponseRules',
        description: 'Test'
    },
    operation: {
        inputFields: generateInputFields(responseRuleCreateInput),
        perform: async (z: ZObject, bundle: InputBundle<typeof responseRuleCreateInput>) => {
            const {
                workspaceId,
                ...responseRule
            } = transformInputData(bundle.inputData);

            const localVarPath = bundle.authData.host + '/workspaces/{workspaceId}/responserules'
                .replace('{' + 'workspaceId' + '}', encodeURIComponent(String(workspaceId)));
            let localVarQueryParameters: any = {};
            let localVarHeaderParams: any = {};

            let localVarFormParams: any = {};
            localVarHeaderParams['Content-Type'] = 'application/vnd.whispir.responserule-v1+json';
            localVarHeaderParams['Accept'] = 'application/vnd.whispir.responserule-v1+json';

            let localVarUseFormData = false;

            const responsePromise = z.request({
                method: 'POST',
                headers: addHeaders(localVarHeaderParams, bundle),
                params: localVarQueryParameters,
                url: localVarPath,
                body: ObjectSerializer.serialize(responseRule, "ResponseRule")
            });
            return responsePromise
                .then(response => {
                    if (response.status && response.status >= 200 && response.status <= 299) {
                            let body = {};
                            
                            // Special case to extract the resource identifier from the `Location` header.
                            const checkLocation = response?.headers?.location?.match(/\/([^\/]+)\/?$/);
                            let id = (checkLocation && checkLocation[1]) ? checkLocation[1] : undefined;
                            
                            return { id, ...body };
                    } else {
                            throw new z.errors.Error(response.data);
                    }
                });
        },
    }
  },
};
